### ISSUE TITLE
Status: unauthorized

### ISSUE THREAD

**Issue by sstepien** [UnifiedID2/uid2docs#26]
I try to play a bit with the API for token generation. When I use curl examples from your documentation I am getting following issue:
{code}
curl -L -X GET 'https://integ.uidapi.com/v1/token/generate?email=username@example.com' -H 'Authorization: Bearer YourTokenBV3tua4BXNw+HVUFpxLlGy8nWN6mtgMlIk='

Response:
{"status":"unauthorized"}
{/code}
What token should I be using and how to get one?

**Comment by hhhmmmlee** [comment]
I got a same response.. how to fix it? :)

**Comment by scong-ttd** [comment]
To avoid leaking sensitive data the API tokens in the example are fake. Please replace them with the API tokens UID2 team provided to test it.
